name: aila
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+22

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.2.0
  intl: ^0.18.0
  synchronized: ^3.1.0
  flutter_screenutil: ^5.8.3
  go_router: ^7.1.1
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  path: ^1.8.3
  path_provider: ^2.1.2
  dio: ^5.1.2
  package_info_plus: ^4.0.2
  connectivity_plus: ^6.0.2
  shared_preferences: ^2.1.1
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_easyloading: ^3.0.5
  progress_indicators: ^1.0.0
  equatable: ^2.0.5
  image: ^4.1.7
  permission_handler: ^11.3.1
  extended_image: ^8.2.0
  wechat_assets_picker: ^9.0.2
  wechat_camera_picker: ^4.2.0
  flutter_sound: ^9.4.6
  audio_session: ^0.1.19

# dependency_overrides:
#   photo_manager: ^3.0.0-dev.5
#   wechat_assets_picker: ^9.0.0-dev.2

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.7.0
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/svgs/

flutter_intl:
  enabled: true

flutter_assets:
  assets_path: assets/
  output_path: lib/assets/
